### ISSUE TITLE
Яндекс.Практикум: Код-ревью

### ISSUE THREAD

**Issue by zlocate** [4lukyanov/form#1]
Здравствуйте. Благодарю за проделанную работу. 
Хочется отметить высокое качество выполнения работы в целом. Регулярные выражения корректно покрывают бОльшую часть кейсов.

К сожалению, в текущей реализации присутствуют недостатки не позволяющие засчитать ее на данной итерации.

Регулярные выражения:
Ссылка на сайт:
Проходят валидацию следующие некорректные адреса:
1. `http://8..8.`
2. `http://8.8.8.`
3. `http://ya.8.`

**Comment by zlocate** [comment]
*Можно лучше:* рекомендую добавить в репозиторий файл .gitignore c правилами исключающими попадание временных файлов в репозиторий. В частности в репозиторий попала директория `__MACOSX`, которую лучше удалить

**Comment by zlocate** [comment]
Добрый день.
Благодарю за оперативность при внесении изменений.
К сожалению, в текущей реализации присутствуют недостатки не позволяющие засчитать ее на данной итерации.

Регулярные выражения:
Ссылка на сайт:
Не проходят валидацию регулярные выражегния, содержащие корректный IP-адрес
http://127.0.0.1
Не проходят валидацию регулярные выражегния, содержащие корректный IP-адрес+порт
http://127.0.0.1:8080

После исправления данных недостатков (при условии что в процессе исправления и дальнейшей проверки не будут выявлены новые) - работа будет зачтена

**Comment by 4lukyanov** [comment]
Добрый день!
Спасибо за оперативную проверку.
Ваши замечания исправил.

**Comment by zlocate** [comment]
Здравствуйте. Выявленные при прошлой проверке проблемы устранены.
Отличная работа!
Желаю вам успехов при дальнейшем прохождении курса.
Еще увидимся! :)
